### Get all credentials
GET http://localhost:3000/api/credentials

### Get single credential
GET http://localhost:3000/api/credentials/ICQ

### Add single credential
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
    "service": "neuefische",
    "username": "philipp",
    "password": "alterfisch"
}

### Delete single credential
DELETE http://localhost:3000/api/credentials/neuefische

### Replace existing credential
PUT http://localhost:3000/api/credentials/MySpace
Content-Type: application/json

{
    "service": "StudiVZ",
    "username": "philipp",
    "password": "alterfisch"
}